# Generated by Django 3.2.6 on 2022-03-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_services_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
