# Generated by Django 3.2.6 on 2022-03-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_services_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=20)),
                ('creditcardno', models.CharField(max_length=20)),
                ('exp', models.CharField(max_length=10)),
                ('ccv', models.CharField(max_length=10)),
            ],
        ),
    ]
